stages:
  - test
  - report


app-test:
  image: amazoncorretto:17-alpine-jdk
  stage: test
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - apk update
    - apk add firefox
  script:
    - chmod +x ./gradlew
    - ./gradlew clean test -Dbrowser=firefox -Dheadless=true

  artifacts:
    when: always
    paths:
      # - build/reports/allure-report/allureReport/widgets/summary.json
     - build/test-results/ # Путь к результатам тестов, используемым Allure для создания отчетов
     - build/reports/tests/
  allow_failure: true

test-report:
  image: amazoncorretto:17-alpine-jdk
  stage: report
  script:
    - ls -lA build
    - chmod +x ./gradlew && ./gradlew allureReport
    - ls -lA build/reports
    - java "-DconfigFile=notifications/config.json" -jar notifications/allure-notifications-4.6.1.jar
