stages:
  - test


app-test:
  image: amazoncorretto:17-alpine-jdk
  stage: test
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - apk update
    - apk add firefox
  script: ./gradlew clean test -Dbrowser=firefox -Dheadless=true