stages:
  - test
  - report


app-test:
  image: amazoncorretto:17-alpine-jdk
  stage: test
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - apk update
    - apk add --no-cache bash curl
    - apk add --no-cache chromium=125.0.6422.76-r0
    - apk add --no-cache chromium-chromedriver=125.0.6422.76-r0
    - export PATH=$PATH:/usr/lib/chromium/
    - echo "Chromium version:"
    - chromium-browser --version
    - echo "ChromeDriver version:"
    - chromedriver --version
  script:
    - chmod +x ./gradlew
    - ./gradlew clean test -Dbrowser=chrome -Dheadless=true

  artifacts:
    when: always
    paths:
      - build/allure-results
      - build/test-results
      - build/reports/tests
  allow_failure: true

test-report:
  image: amazoncorretto:17-alpine-jdk
  stage: report
  script:
    - apk add --no-cache msttcorefonts-installer fontconfig && update-ms-fonts
    - chmod +x ./gradlew && ./gradlew allureReport
    - java "-DconfigFile=notifications/config.json" -jar notifications/allure-notifications-4.6.1.jar
