stages:
  - test


app-test:
  image: amazoncorretto:17-alpine-jdk
  stage: test
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - apk update
    - apk add firefox
  script:
    - chmod +x ./gradlew
    - ./gradlew clean test -Dbrowser=firefox -Dheadless=true
    - ./gradlew io.qameta.allure:allure-maven:report
