stages:
  - test
  - report


app-test:
  image: amazoncorretto:17-alpine-jdk
  stage: test
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - apk update
    - apk add firefox
  script:
    - chmod +x ./gradlew
    - ./gradlew clean test -Dbrowser=firefox -Dheadless=true
    - ./gradlew allure:report # Генерация отчетов Allure
  artifacts:
        when: always
        paths:
          - build/allure-results/ # Путь к результатам тестов, используемым Allure для создания отчетов
          - build/reports/allure-report/

test-report:
  image: amazoncorretto:17-alpine-jdk
  stage: report
  script:
    - cp "$ALLURE_CONFIG" config.json
    - wget https://github.com/qa-guru/allure-notifications/releases/download/4.6.1/allure-notifications-4.6.1.jar
    - java "-DconfigFile=config.json" -jar allure-notifications-4.6.1.jar